#!/usr/bin/env bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${GREEN}Building Vais Documentation Site (Multilingual)${NC}"
echo "======================================"

# Check if mdbook is installed
if ! command -v mdbook &> /dev/null; then
    echo -e "${YELLOW}mdBook not found. Installing...${NC}"
    cargo install mdbook
fi

# Check if mdbook-linkcheck is installed (optional but recommended)
if ! command -v mdbook-linkcheck &> /dev/null; then
    echo -e "${YELLOW}mdbook-linkcheck not found. Installing...${NC}"
    cargo install mdbook-linkcheck
fi

# Navigate to docs-site directory
cd "$(dirname "$0")"

# Clean previous build
echo -e "${GREEN}Cleaning previous build...${NC}"
rm -rf book/

# Define languages
LANGUAGES="ko en ja zh"

# Language display name lookup (Bash 3.2 compatible — no associative arrays)
lang_name() {
    case "$1" in
        ko) echo "한국어 (Korean)" ;;
        en) echo "English" ;;
        ja) echo "日本語 (Japanese)" ;;
        zh) echo "中文 (Chinese)" ;;
    esac
}

# Language description lookup
lang_desc() {
    case "$1" in
        ko) echo "공식 Vais 프로그래밍 언어 문서" ;;
        en) echo "Official Vais Programming Language Documentation" ;;
        ja) echo "公式Vaisプログラミング言語ドキュメント" ;;
        zh) echo "官方Vais编程语言文档" ;;
    esac
}

# Build each language
for lang in $LANGUAGES; do
    DISPLAY_NAME="$(lang_name "$lang")"
    echo ""
    echo -e "${BLUE}Building ${DISPLAY_NAME}...${NC}"

    if [ "$lang" = "ko" ]; then
        # Korean is default - use existing book.toml and src/
        echo -e "  Using default configuration (src/)"
        mdbook build
        echo -e "${GREEN}✓ Korean documentation built successfully!${NC}"
    else
        # For other languages, create temporary book.toml
        TEMP_CONFIG="book.${lang}.toml"

        echo -e "  Creating temporary config: ${TEMP_CONFIG}"

        DESCRIPTION="$(lang_desc "$lang")"

        cat > "${TEMP_CONFIG}" <<EOF
# Temporary configuration for ${DISPLAY_NAME} documentation
# Generated by build.sh - do not edit manually

[book]
title = "Vais Programming Language"
description = "${DESCRIPTION}"
authors = ["Vais Contributors"]
language = "${lang}"
src = "src/${lang}"

[build]
build-dir = "book/${lang}"
create-missing = false

[preprocessor.links]

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/vaislang/vais"
edit-url-template = "https://github.com/vaislang/vais/edit/main/{path}"
site-url = "/docs/${lang}/"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = false
runnable = false
EOF

        # Backup original book.toml and use temp config
        if [ -f "book.toml" ]; then
            mv book.toml book.toml.backup
        fi
        mv "${TEMP_CONFIG}" book.toml

        # Build with temporary config (restored on success or failure)
        if mdbook build; then
            echo -e "${GREEN}✓ ${DISPLAY_NAME} documentation built successfully!${NC}"
        else
            echo -e "${RED}✗ Failed to build ${DISPLAY_NAME} documentation${NC}"
            # Restore original config and exit
            if [ -f "book.toml.backup" ]; then
                mv book.toml.backup book.toml
            fi
            exit 1
        fi

        # Restore original config
        if [ -f "book.toml.backup" ]; then
            mv book.toml.backup book.toml
        fi
    fi
done

# Create index.html for language selection
echo ""
echo -e "${BLUE}Creating language selector index...${NC}"

cat > book/index.html <<'EOF'
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vais Programming Language Documentation</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            color: #fff;
        }
        .container {
            max-width: 800px;
            padding: 3rem;
            text-align: center;
        }
        h1 {
            font-size: 3rem;
            margin-bottom: 1rem;
            font-weight: 700;
        }
        .subtitle {
            font-size: 1.2rem;
            margin-bottom: 3rem;
            opacity: 0.9;
        }
        .languages {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
            gap: 1.5rem;
            margin-top: 2rem;
        }
        .language-card {
            background: rgba(255, 255, 255, 0.1);
            backdrop-filter: blur(10px);
            border: 1px solid rgba(255, 255, 255, 0.2);
            border-radius: 12px;
            padding: 2rem 1.5rem;
            text-decoration: none;
            color: #fff;
            transition: all 0.3s ease;
            display: flex;
            flex-direction: column;
            align-items: center;
            gap: 0.5rem;
        }
        .language-card:hover {
            background: rgba(255, 255, 255, 0.2);
            transform: translateY(-5px);
            box-shadow: 0 10px 30px rgba(0, 0, 0, 0.3);
        }
        .language-flag {
            font-size: 3rem;
            margin-bottom: 0.5rem;
        }
        .language-name {
            font-size: 1.3rem;
            font-weight: 600;
        }
        .language-native {
            font-size: 1rem;
            opacity: 0.8;
        }
        footer {
            margin-top: 3rem;
            opacity: 0.7;
            font-size: 0.9rem;
        }
        footer a {
            color: #fff;
            text-decoration: none;
            border-bottom: 1px solid rgba(255, 255, 255, 0.3);
        }
        footer a:hover {
            border-bottom-color: #fff;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Vais</h1>
        <p class="subtitle">AI-Optimized Systems Programming Language</p>

        <div class="languages">
            <a href="./introduction.html" class="language-card">
                <div class="language-flag">🇰🇷</div>
                <div class="language-name">한국어</div>
                <div class="language-native">Korean</div>
            </a>

            <a href="./en/index.html" class="language-card">
                <div class="language-flag">🇬🇧</div>
                <div class="language-name">English</div>
                <div class="language-native">English</div>
            </a>

            <a href="./ja/index.html" class="language-card">
                <div class="language-flag">🇯🇵</div>
                <div class="language-name">日本語</div>
                <div class="language-native">Japanese</div>
            </a>

            <a href="./zh/index.html" class="language-card">
                <div class="language-flag">🇨🇳</div>
                <div class="language-name">中文</div>
                <div class="language-native">Chinese</div>
            </a>
        </div>

        <footer>
            <p>
                <a href="https://github.com/vaislang/vais" target="_blank">GitHub</a> •
                <a href="https://github.com/vaislang/vais/issues" target="_blank">Issues</a> •
                MIT License
            </p>
        </footer>
    </div>
</body>
</html>
EOF

echo -e "${GREEN}✓ Language selector created!${NC}"

# Summary
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}✓ All documentation built successfully!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Output directories:"
echo -e "  ${YELLOW}Korean (ko):${NC}   $(pwd)/book/"
echo -e "  ${YELLOW}English (en):${NC}  $(pwd)/book/en/"
echo -e "  ${YELLOW}Japanese (ja):${NC} $(pwd)/book/ja/"
echo -e "  ${YELLOW}Chinese (zh):${NC}  $(pwd)/book/zh/"
echo ""
echo "To view the documentation locally, run:"
echo -e "  ${YELLOW}mdbook serve${NC}"
echo ""
echo -e "Or open: ${YELLOW}$(pwd)/book/index.html${NC}"
