#!/usr/bin/env bash

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${GREEN}Building Vais Documentation Site (Multilingual)${NC}"
echo "======================================"

# Check if mdbook is installed
if ! command -v mdbook &> /dev/null; then
    echo -e "${YELLOW}mdBook not found. Installing...${NC}"
    cargo install mdbook
fi

# Check if mdbook-linkcheck is installed (optional but recommended)
if ! command -v mdbook-linkcheck &> /dev/null; then
    echo -e "${YELLOW}mdbook-linkcheck not found. Installing...${NC}"
    cargo install mdbook-linkcheck
fi

# Navigate to docs-site directory
cd "$(dirname "$0")"

# Clean previous build
echo -e "${GREEN}Cleaning previous build...${NC}"
rm -rf book/

# Define languages
LANGUAGES="ko en ja zh"

# Language display name lookup (Bash 3.2 compatible — no associative arrays)
lang_name() {
    case "$1" in
        ko) echo "한국어 (Korean)" ;;
        en) echo "English" ;;
        ja) echo "日本語 (Japanese)" ;;
        zh) echo "中文 (Chinese)" ;;
    esac
}

# Language description lookup
lang_desc() {
    case "$1" in
        ko) echo "공식 Vais 프로그래밍 언어 문서" ;;
        en) echo "Official Vais Programming Language Documentation" ;;
        ja) echo "公式Vaisプログラミング言語ドキュメント" ;;
        zh) echo "官方Vais编程语言文档" ;;
    esac
}

# Build each language
for lang in $LANGUAGES; do
    DISPLAY_NAME="$(lang_name "$lang")"
    echo ""
    echo -e "${BLUE}Building ${DISPLAY_NAME}...${NC}"

    if [ "$lang" = "ko" ]; then
        # Korean is default - use existing book.toml and src/
        echo -e "  Using default configuration (src/)"
        mdbook build
        echo -e "${GREEN}✓ Korean documentation built successfully!${NC}"
    else
        # For other languages, create temporary book.toml
        TEMP_CONFIG="book.${lang}.toml"

        echo -e "  Creating temporary config: ${TEMP_CONFIG}"

        DESCRIPTION="$(lang_desc "$lang")"

        cat > "${TEMP_CONFIG}" <<EOF
# Temporary configuration for ${DISPLAY_NAME} documentation
# Generated by build.sh - do not edit manually

[book]
title = "Vais Programming Language"
description = "${DESCRIPTION}"
authors = ["Vais Contributors"]
language = "${lang}"
src = "src/${lang}"

[build]
build-dir = "book/${lang}"
create-missing = false

[preprocessor.links]

[output.html]
default-theme = "dark"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/vaislang/vais"
edit-url-template = "https://github.com/vaislang/vais/edit/main/{path}"
site-url = "/docs/${lang}/"
additional-css = ["theme/lang-selector.css"]
additional-js = ["theme/lang-selector.js"]

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.fold]
enable = true
level = 0

[output.html.playground]
editable = true
copyable = true
copy-js = true
line-numbers = false
runnable = false
EOF

        # Backup original book.toml and use temp config
        if [ -f "book.toml" ]; then
            mv book.toml book.toml.backup
        fi
        mv "${TEMP_CONFIG}" book.toml

        # Build with temporary config (restored on success or failure)
        if mdbook build; then
            echo -e "${GREEN}✓ ${DISPLAY_NAME} documentation built successfully!${NC}"
        else
            echo -e "${RED}✗ Failed to build ${DISPLAY_NAME} documentation${NC}"
            # Restore original config and exit
            if [ -f "book.toml.backup" ]; then
                mv book.toml.backup book.toml
            fi
            exit 1
        fi

        # Restore original config
        if [ -f "book.toml.backup" ]; then
            mv book.toml.backup book.toml
        fi
    fi
done

# Create index.html for language selection
echo ""
echo -e "${BLUE}Creating language selector index...${NC}"

cat > book/index.html <<'INDEXEOF'
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="0;url=./introduction.html">
    <title>Vais Documentation</title>
</head>
<body>
    <p>Redirecting to <a href="./introduction.html">한국어 문서</a>...</p>
</body>
</html>
INDEXEOF

echo -e "${GREEN}✓ Language selector created!${NC}"

# Summary
echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}✓ All documentation built successfully!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "Output directories:"
echo -e "  ${YELLOW}Korean (ko):${NC}   $(pwd)/book/"
echo -e "  ${YELLOW}English (en):${NC}  $(pwd)/book/en/"
echo -e "  ${YELLOW}Japanese (ja):${NC} $(pwd)/book/ja/"
echo -e "  ${YELLOW}Chinese (zh):${NC}  $(pwd)/book/zh/"
echo ""
echo "To view the documentation locally, run:"
echo -e "  ${YELLOW}mdbook serve${NC}"
echo ""
echo -e "Or open: ${YELLOW}$(pwd)/book/index.html${NC}"
