title: "[Idea] "
labels: ["idea", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea! We love hearing feature suggestions and improvements from the Vais community.

        Please describe your feature idea below. Make sure it's clear what problem you're trying to solve and how your idea would help.

  - type: textarea
    attributes:
      label: Feature Description
      description: Describe the feature or improvement you'd like to propose
      placeholder: |
        What feature would you like to see in Vais? Why would this be valuable?

        Example: "We could add pattern matching for algebraic data types to make functional programming patterns more ergonomic..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: |
        Describe the pain point or limitation that your feature would address.

        Example: "Currently, there's no idiomatic way to handle multiple return types without using Result wrappers..."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Cases
      description: Provide concrete use cases or examples
      placeholder: |
        - Use case 1: ...
        - Use case 2: ...
        - Real-world scenario: ...

  - type: textarea
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or implementation approach
      placeholder: |
        How would you implement this? What would the API or syntax look like?

  - type: textarea
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or workarounds exist?

  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this idea, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
