#!/usr/bin/env node

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const registryPath = 'docs/ai/feature-registry.json';
const registry = JSON.parse(readFileSync(resolve(root, registryPath), 'utf8'));
const checkOnly = process.argv.includes('--check');

const generatedNotice = `<!-- Generated by scripts/generate-ai-docs.mjs from ${registryPath}. Do not edit by hand. -->`;

function bullet(items) {
  return items.map((item) => `- ${item}`).join('\n');
}

function escapeText(text) {
  return text.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

function inlineCodeList(items) {
  return items.map((item) => `\`${item}\``).join(', ');
}

function statusLabel(status) {
  switch (status) {
    case 'certified-core':
      return 'certified core';
    case 'evidence-scoped':
      return 'evidence scoped';
    case 'workbench':
      return 'workbench';
    case 'non-claim':
      return 'non-claim';
    default:
      return status;
  }
}

function featureBlock(feature, heading = '###') {
  return `${heading} ${feature.title}

Feature id: \`${feature.id}\`

Status: ${statusLabel(feature.status)}

${escapeText(feature.summary)}

AI instructions:

${bullet(feature.aiInstructions.map(escapeText))}

Use:

${bullet(feature.mustUse.map((item) => `\`${item}\``))}

Avoid:

${bullet(feature.avoid.map(escapeText))}
`;
}

function renderLanguageCard() {
  return `${generatedNotice}

# Vais LLM Language Card

Last reviewed: ${registry.lastReviewed}

This is the short, AI-facing contract for writing Vais code. It is generated
from \`${registryPath}\`; update that registry and regenerate this file when the
language, compiler, playground, DB, server, or web surface changes.

## Read Order

1. \`docs/ai/LLM_LANGUAGE_CARD.md\`
2. \`docs/LANGUAGE_SPEC.md\`
3. \`PUBLIC_STATUS.md\`
4. \`docs/ai/AI_DEVELOPER_GUIDE.md\`

## Non-Negotiable Rules

- Do not rely on model memory for Vais syntax.
- Do not translate Vais into Rust, TypeScript, C, or pseudocode.
- Use canonical public syntax from \`docs/LANGUAGE_SPEC.md\`.
- Treat DB, server, web, and playground claims as evidence-scoped unless
  \`PUBLIC_STATUS.md\` names a stronger gate.
- If compiler output disagrees with this card, stop and update the docs or the
  compiler instead of inventing silent fallback behavior.

## Feature Contract

${registry.features.map((feature) => featureBlock(feature)).join('\n')}

## Minimal Current Syntax

\`\`\`vais
fn checked_div(a: i64, b: i64) -> Result<i64, str> {
    I b == 0 {
        return Err("division by zero")
    }
    Ok(a / b)
}

fn unwrap_or_zero(opt: Option<i64>) -> i64 {
    match opt {
        Some(v) => v,
        None => 0,
    }
}
\`\`\`
`;
}

function renderDeveloperGuide() {
  return `${generatedNotice}

# Vais AI Developer Guide

Last reviewed: ${registry.lastReviewed}

This guide is for AI agents that do not already know Vais. The expected workflow
is documentation-first, compile-second, and claim-last.

## Workflow

1. Read \`docs/ai/LLM_LANGUAGE_CARD.md\`.
2. Read the relevant section of \`docs/LANGUAGE_SPEC.md\`.
3. Check public status in \`PUBLIC_STATUS.md\` before making ecosystem claims.
4. Write the smallest Vais code that exercises the requested behavior.
5. Run the narrowest compiler/test gate that can reject the change.
6. Broaden to package or CI gates only after the narrow gate passes.

## Commands

\`\`\`bash
cargo fmt --all -- --check
cargo test -p vais-types --test inference_unification_tests -- --nocapture
cargo test -p vaisc --test e2e -- --nocapture
node scripts/check-public-claims.mjs
node scripts/check-ai-docs-sync.mjs
\`\`\`

## Feature Checklist

${registry.features
  .map(
    (feature) => `- \`${feature.id}\`: ${escapeText(feature.summary)} Status: ${statusLabel(feature.status)}.`,
  )
  .join('\n')}

## Failure Handling

- Syntax error: compare the source with \`docs/LANGUAGE_SPEC.md\` before trying
  another spelling.
- Type error: preserve explicit type boundaries; do not add implicit coercions.
- Layout or IR error: check enum, pointer, slice, and reference lowering first.
- Public claim mismatch: update \`PUBLIC_STATUS.md\`, the registry, and generated
  AI docs in the same change.
- Playground mismatch: name the exact mode and API dependency.

## Updating These Docs

When a feature is added or behavior changes:

1. Edit \`${registryPath}\`.
2. Run \`node scripts/generate-ai-docs.mjs\`.
3. Run \`node scripts/check-ai-docs-sync.mjs\`.
4. Include the generated docs and registry in the same PR as the behavior
   change.

The CI drift check fails pull requests that modify language/compiler/public
surface paths without touching the AI docs registry.
`;
}

function renderReferenceAppContract() {
  const requiredFeatures = registry.features.filter((feature) => feature.referenceApp);
  const referenceApp = registry.referenceApp;

  return `${generatedNotice}

# Vais Reference App Contract

Last reviewed: ${registry.lastReviewed}

The reference app is the end-to-end validation target for AI-written Vais code.
It should be small enough for a new AI agent to understand from official docs,
but broad enough to exercise the language, compiler, DB, server, web, and
playground boundaries that public docs mention.

## Required Coverage

${requiredFeatures
  .map(
    (feature) => `- \`${feature.id}\`: ${escapeText(feature.summary)}`,
  )
  .join('\n')}

## Suggested App Shape

- A task or notes service with list, detail, create, update, and delete flows.
- A schema fixture that can be reused by compiler, DB, server, and web tests.
- Result-returning validation functions and Option-returning lookup functions.
- Match-heavy control flow for empty, found, validation-error, and storage-error
  cases.
- At least one explicit pointer/raw-address boundary test if low-level APIs are
  involved.
- A playground example extracted from the same source pattern.

## Current Reference App

Name: ${escapeText(referenceApp.name)}

Path: \`${referenceApp.path}\`

Gate: \`${referenceApp.gate}\`

${escapeText(referenceApp.description)}

## Acceptance Gates

\`\`\`bash
cargo fmt --all -- --check
cargo test -p vais-types --test inference_unification_tests -- --nocapture
cargo test -p vaisc --test e2e -- --nocapture
node scripts/check-public-claims.mjs
node scripts/check-ai-docs-sync.mjs
bash ${referenceApp.gate}
\`\`\`

The reference app is complete only when a clean checkout can build and test it
without relying on unstated AI memory.
`;
}

const outputs = new Map([
  ['docs/ai/LLM_LANGUAGE_CARD.md', renderLanguageCard()],
  ['docs/ai/AI_DEVELOPER_GUIDE.md', renderDeveloperGuide()],
  ['docs/ai/REFERENCE_APP_CONTRACT.md', renderReferenceAppContract()],
]);

const mismatches = [];
for (const [path, content] of outputs) {
  const absPath = resolve(root, path);
  if (checkOnly) {
    let current = '';
    try {
      current = readFileSync(absPath, 'utf8');
    } catch {
      mismatches.push(`${path}: missing generated file`);
      continue;
    }
    if (current !== content) {
      mismatches.push(`${path}: generated content is stale; run node scripts/generate-ai-docs.mjs`);
    }
  } else {
    writeFileSync(absPath, content);
  }
}

if (mismatches.length > 0) {
  for (const mismatch of mismatches) {
    console.error(mismatch);
  }
  process.exit(1);
}

if (!checkOnly) {
  console.log(`Generated ${outputs.size} AI docs from ${registryPath}.`);
}
