//! Built-in function definitions for LSP completion and documentation

/// Built-in function info
pub struct BuiltinFn {
    pub name: &'static str,
    pub params: &'static str,
    pub return_type: &'static str,
    pub description: &'static str,
    pub snippet: &'static str,
    pub category: &'static str,
}

/// All built-in functions with documentation
pub const BUILTIN_FUNCTIONS: &[BuiltinFn] = &[
    // === Core ===
    BuiltinFn {
        name: "print",
        params: "value: Any",
        return_type: "Void",
        description: "Print value to stdout",
        snippet: "print($0)",
        category: "core",
    },
    BuiltinFn {
        name: "len",
        params: "value: String|Array|Map",
        return_type: "Int",
        description: "Get length of string, array, or map",
        snippet: "len($0)",
        category: "core",
    },
    BuiltinFn {
        name: "type_of",
        params: "value: Any",
        return_type: "String",
        description: "Get type name of value",
        snippet: "type_of($0)",
        category: "core",
    },
    BuiltinFn {
        name: "to_string",
        params: "value: Any",
        return_type: "String",
        description: "Convert value to string",
        snippet: "to_string($0)",
        category: "core",
    },
    BuiltinFn {
        name: "to_int",
        params: "value: String|Float",
        return_type: "Int",
        description: "Convert to integer",
        snippet: "to_int($0)",
        category: "core",
    },
    BuiltinFn {
        name: "to_float",
        params: "value: String|Int",
        return_type: "Float",
        description: "Convert to float",
        snippet: "to_float($0)",
        category: "core",
    },

    // === Math ===
    BuiltinFn {
        name: "abs",
        params: "n: Int|Float",
        return_type: "Int|Float",
        description: "Absolute value",
        snippet: "abs($0)",
        category: "math",
    },
    BuiltinFn {
        name: "sqrt",
        params: "n: Float",
        return_type: "Float",
        description: "Square root",
        snippet: "sqrt($0)",
        category: "math",
    },
    BuiltinFn {
        name: "pow",
        params: "base: Float, exp: Float",
        return_type: "Float",
        description: "Power function",
        snippet: "pow($1, $2)",
        category: "math",
    },
    BuiltinFn {
        name: "min",
        params: "a: Int|Float, b: Int|Float",
        return_type: "Int|Float",
        description: "Minimum of two values",
        snippet: "min($1, $2)",
        category: "math",
    },
    BuiltinFn {
        name: "max",
        params: "a: Int|Float, b: Int|Float",
        return_type: "Int|Float",
        description: "Maximum of two values",
        snippet: "max($1, $2)",
        category: "math",
    },
    BuiltinFn {
        name: "floor",
        params: "n: Float",
        return_type: "Int",
        description: "Floor (round down)",
        snippet: "floor($0)",
        category: "math",
    },
    BuiltinFn {
        name: "ceil",
        params: "n: Float",
        return_type: "Int",
        description: "Ceiling (round up)",
        snippet: "ceil($0)",
        category: "math",
    },
    BuiltinFn {
        name: "round",
        params: "n: Float",
        return_type: "Int",
        description: "Round to nearest integer",
        snippet: "round($0)",
        category: "math",
    },
    BuiltinFn {
        name: "sin",
        params: "n: Float",
        return_type: "Float",
        description: "Sine function",
        snippet: "sin($0)",
        category: "math",
    },
    BuiltinFn {
        name: "cos",
        params: "n: Float",
        return_type: "Float",
        description: "Cosine function",
        snippet: "cos($0)",
        category: "math",
    },
    BuiltinFn {
        name: "tan",
        params: "n: Float",
        return_type: "Float",
        description: "Tangent function",
        snippet: "tan($0)",
        category: "math",
    },
    BuiltinFn {
        name: "log",
        params: "n: Float",
        return_type: "Float",
        description: "Natural logarithm",
        snippet: "log($0)",
        category: "math",
    },
    BuiltinFn {
        name: "exp",
        params: "n: Float",
        return_type: "Float",
        description: "Exponential function (e^n)",
        snippet: "exp($0)",
        category: "math",
    },

    // === String ===
    BuiltinFn {
        name: "concat",
        params: "a: String, b: String",
        return_type: "String",
        description: "Concatenate strings",
        snippet: "concat($1, $2)",
        category: "string",
    },
    BuiltinFn {
        name: "split",
        params: "s: String, sep: String",
        return_type: "Array<String>",
        description: "Split string by separator",
        snippet: "split($1, $2)",
        category: "string",
    },
    BuiltinFn {
        name: "join",
        params: "arr: Array<String>, sep: String",
        return_type: "String",
        description: "Join array with separator",
        snippet: "join($1, $2)",
        category: "string",
    },
    BuiltinFn {
        name: "trim",
        params: "s: String",
        return_type: "String",
        description: "Trim whitespace from both ends",
        snippet: "trim($0)",
        category: "string",
    },
    BuiltinFn {
        name: "upper",
        params: "s: String",
        return_type: "String",
        description: "Convert to uppercase",
        snippet: "upper($0)",
        category: "string",
    },
    BuiltinFn {
        name: "lower",
        params: "s: String",
        return_type: "String",
        description: "Convert to lowercase",
        snippet: "lower($0)",
        category: "string",
    },
    BuiltinFn {
        name: "contains",
        params: "s: String, sub: String",
        return_type: "Bool",
        description: "Check if string contains substring",
        snippet: "contains($1, $2)",
        category: "string",
    },
    BuiltinFn {
        name: "starts_with",
        params: "s: String, prefix: String",
        return_type: "Bool",
        description: "Check if string starts with prefix",
        snippet: "starts_with($1, $2)",
        category: "string",
    },
    BuiltinFn {
        name: "ends_with",
        params: "s: String, suffix: String",
        return_type: "Bool",
        description: "Check if string ends with suffix",
        snippet: "ends_with($1, $2)",
        category: "string",
    },
    BuiltinFn {
        name: "replace",
        params: "s: String, from: String, to: String",
        return_type: "String",
        description: "Replace occurrences in string",
        snippet: "replace($1, $2, $3)",
        category: "string",
    },
    BuiltinFn {
        name: "substring",
        params: "s: String, start: Int, end: Int",
        return_type: "String",
        description: "Get substring from start to end",
        snippet: "substring($1, $2, $3)",
        category: "string",
    },
    BuiltinFn {
        name: "char_at",
        params: "s: String, index: Int",
        return_type: "String",
        description: "Get character at index",
        snippet: "char_at($1, $2)",
        category: "string",
    },
    BuiltinFn {
        name: "index_of",
        params: "s: String, sub: String",
        return_type: "Int",
        description: "Find index of substring (-1 if not found)",
        snippet: "index_of($1, $2)",
        category: "string",
    },

    // === Array ===
    BuiltinFn {
        name: "push",
        params: "arr: Array, item: Any",
        return_type: "Array",
        description: "Add item to end of array",
        snippet: "push($1, $2)",
        category: "array",
    },
    BuiltinFn {
        name: "pop",
        params: "arr: Array",
        return_type: "Any",
        description: "Remove and return last item",
        snippet: "pop($0)",
        category: "array",
    },
    BuiltinFn {
        name: "first",
        params: "arr: Array",
        return_type: "Any",
        description: "Get first element",
        snippet: "first($0)",
        category: "array",
    },
    BuiltinFn {
        name: "last",
        params: "arr: Array",
        return_type: "Any",
        description: "Get last element",
        snippet: "last($0)",
        category: "array",
    },
    BuiltinFn {
        name: "take",
        params: "arr: Array, n: Int",
        return_type: "Array",
        description: "Take first n elements",
        snippet: "take($1, $2)",
        category: "array",
    },
    BuiltinFn {
        name: "drop",
        params: "arr: Array, n: Int",
        return_type: "Array",
        description: "Drop first n elements",
        snippet: "drop($1, $2)",
        category: "array",
    },
    BuiltinFn {
        name: "reverse",
        params: "arr: Array",
        return_type: "Array",
        description: "Reverse array",
        snippet: "reverse($0)",
        category: "array",
    },
    BuiltinFn {
        name: "sort",
        params: "arr: Array",
        return_type: "Array",
        description: "Sort array",
        snippet: "sort($0)",
        category: "array",
    },
    BuiltinFn {
        name: "range",
        params: "start: Int, end: Int",
        return_type: "Array<Int>",
        description: "Create range [start, end)",
        snippet: "range($1, $2)",
        category: "array",
    },
    BuiltinFn {
        name: "flatten",
        params: "arr: Array<Array>",
        return_type: "Array",
        description: "Flatten nested array",
        snippet: "flatten($0)",
        category: "array",
    },
    BuiltinFn {
        name: "zip",
        params: "a: Array, b: Array",
        return_type: "Array<Array>",
        description: "Zip two arrays together",
        snippet: "zip($1, $2)",
        category: "array",
    },
    BuiltinFn {
        name: "enumerate",
        params: "arr: Array",
        return_type: "Array<Array>",
        description: "Add index to each element",
        snippet: "enumerate($0)",
        category: "array",
    },

    // === std.io - File I/O ===
    BuiltinFn {
        name: "read_file",
        params: "path: String",
        return_type: "String|Error",
        description: "Read file content as string",
        snippet: "read_file($0)",
        category: "io",
    },
    BuiltinFn {
        name: "read_file_bytes",
        params: "path: String",
        return_type: "Bytes|Error",
        description: "Read file content as bytes",
        snippet: "read_file_bytes($0)",
        category: "io",
    },
    BuiltinFn {
        name: "read_lines",
        params: "path: String",
        return_type: "Array<String>|Error",
        description: "Read file as array of lines",
        snippet: "read_lines($0)",
        category: "io",
    },
    BuiltinFn {
        name: "write_file",
        params: "path: String, content: String",
        return_type: "Bool|Error",
        description: "Write content to file",
        snippet: "write_file($1, $2)",
        category: "io",
    },
    BuiltinFn {
        name: "append_file",
        params: "path: String, content: String",
        return_type: "Bool|Error",
        description: "Append content to file",
        snippet: "append_file($1, $2)",
        category: "io",
    },

    // === std.io - Path ===
    BuiltinFn {
        name: "path_exists",
        params: "path: String",
        return_type: "Bool",
        description: "Check if path exists",
        snippet: "path_exists($0)",
        category: "io",
    },
    BuiltinFn {
        name: "path_is_file",
        params: "path: String",
        return_type: "Bool",
        description: "Check if path is a file",
        snippet: "path_is_file($0)",
        category: "io",
    },
    BuiltinFn {
        name: "path_is_dir",
        params: "path: String",
        return_type: "Bool",
        description: "Check if path is a directory",
        snippet: "path_is_dir($0)",
        category: "io",
    },
    BuiltinFn {
        name: "path_join",
        params: "...parts: String",
        return_type: "String",
        description: "Join path components",
        snippet: "path_join($1, $2)",
        category: "io",
    },
    BuiltinFn {
        name: "path_parent",
        params: "path: String",
        return_type: "String",
        description: "Get parent directory",
        snippet: "path_parent($0)",
        category: "io",
    },
    BuiltinFn {
        name: "path_filename",
        params: "path: String",
        return_type: "String",
        description: "Get file name",
        snippet: "path_filename($0)",
        category: "io",
    },
    BuiltinFn {
        name: "path_extension",
        params: "path: String",
        return_type: "String",
        description: "Get file extension",
        snippet: "path_extension($0)",
        category: "io",
    },
    BuiltinFn {
        name: "path_stem",
        params: "path: String",
        return_type: "String",
        description: "Get file name without extension",
        snippet: "path_stem($0)",
        category: "io",
    },
    BuiltinFn {
        name: "path_absolute",
        params: "path: String",
        return_type: "String|Error",
        description: "Get absolute path",
        snippet: "path_absolute($0)",
        category: "io",
    },

    // === std.io - Directory ===
    BuiltinFn {
        name: "list_dir",
        params: "path: String",
        return_type: "Array<String>|Error",
        description: "List directory contents",
        snippet: "list_dir($0)",
        category: "io",
    },
    BuiltinFn {
        name: "create_dir",
        params: "path: String",
        return_type: "Bool|Error",
        description: "Create directory",
        snippet: "create_dir($0)",
        category: "io",
    },
    BuiltinFn {
        name: "create_dir_all",
        params: "path: String",
        return_type: "Bool|Error",
        description: "Create directory and parents",
        snippet: "create_dir_all($0)",
        category: "io",
    },
    BuiltinFn {
        name: "remove_file",
        params: "path: String",
        return_type: "Bool|Error",
        description: "Remove file",
        snippet: "remove_file($0)",
        category: "io",
    },
    BuiltinFn {
        name: "remove_dir",
        params: "path: String",
        return_type: "Bool|Error",
        description: "Remove empty directory",
        snippet: "remove_dir($0)",
        category: "io",
    },
    BuiltinFn {
        name: "remove_dir_all",
        params: "path: String",
        return_type: "Bool|Error",
        description: "Remove directory recursively",
        snippet: "remove_dir_all($0)",
        category: "io",
    },
    BuiltinFn {
        name: "copy_file",
        params: "src: String, dst: String",
        return_type: "Int|Error",
        description: "Copy file, returns bytes copied",
        snippet: "copy_file($1, $2)",
        category: "io",
    },
    BuiltinFn {
        name: "rename",
        params: "src: String, dst: String",
        return_type: "Bool|Error",
        description: "Rename file or directory",
        snippet: "rename($1, $2)",
        category: "io",
    },
    BuiltinFn {
        name: "file_size",
        params: "path: String",
        return_type: "Int|Error",
        description: "Get file size in bytes",
        snippet: "file_size($0)",
        category: "io",
    },

    // === std.io - Environment ===
    BuiltinFn {
        name: "cwd",
        params: "",
        return_type: "String|Error",
        description: "Get current working directory",
        snippet: "cwd()",
        category: "io",
    },
    BuiltinFn {
        name: "chdir",
        params: "path: String",
        return_type: "Bool|Error",
        description: "Change current directory",
        snippet: "chdir($0)",
        category: "io",
    },
    BuiltinFn {
        name: "env_get",
        params: "key: String",
        return_type: "String|None",
        description: "Get environment variable",
        snippet: "env_get($0)",
        category: "io",
    },
    BuiltinFn {
        name: "env_set",
        params: "key: String, value: String",
        return_type: "Bool",
        description: "Set environment variable",
        snippet: "env_set($1, $2)",
        category: "io",
    },
    BuiltinFn {
        name: "readline",
        params: "",
        return_type: "String|Error",
        description: "Read line from stdin",
        snippet: "readline()",
        category: "io",
    },

    // === std.json ===
    BuiltinFn {
        name: "json_parse",
        params: "s: String",
        return_type: "Any|Error",
        description: "Parse JSON string to value",
        snippet: "json_parse($0)",
        category: "json",
    },
    BuiltinFn {
        name: "json_stringify",
        params: "value: Any",
        return_type: "String",
        description: "Convert value to JSON string",
        snippet: "json_stringify($0)",
        category: "json",
    },
    BuiltinFn {
        name: "json_stringify_pretty",
        params: "value: Any",
        return_type: "String",
        description: "Convert value to pretty-printed JSON",
        snippet: "json_stringify_pretty($0)",
        category: "json",
    },
    BuiltinFn {
        name: "json_get",
        params: "obj: Map, path: String",
        return_type: "Any",
        description: "Get value at JSON path (e.g., \"user.name\")",
        snippet: "json_get($1, \"$2\")",
        category: "json",
    },
    BuiltinFn {
        name: "json_set",
        params: "obj: Map, path: String, value: Any",
        return_type: "Map",
        description: "Set value at JSON path",
        snippet: "json_set($1, \"$2\", $3)",
        category: "json",
    },
    BuiltinFn {
        name: "json_keys",
        params: "obj: Map",
        return_type: "Array<String>",
        description: "Get all keys of object",
        snippet: "json_keys($0)",
        category: "json",
    },
    BuiltinFn {
        name: "json_values",
        params: "obj: Map",
        return_type: "Array",
        description: "Get all values of object",
        snippet: "json_values($0)",
        category: "json",
    },
    BuiltinFn {
        name: "json_has",
        params: "obj: Map, path: String",
        return_type: "Bool",
        description: "Check if path exists in object",
        snippet: "json_has($1, \"$2\")",
        category: "json",
    },
    BuiltinFn {
        name: "json_remove",
        params: "obj: Map, key: String",
        return_type: "Map",
        description: "Remove key from object",
        snippet: "json_remove($1, \"$2\")",
        category: "json",
    },
    BuiltinFn {
        name: "json_merge",
        params: "a: Map, b: Map",
        return_type: "Map",
        description: "Merge two objects",
        snippet: "json_merge($1, $2)",
        category: "json",
    },
    BuiltinFn {
        name: "json_type",
        params: "value: Any",
        return_type: "String",
        description: "Get JSON type name",
        snippet: "json_type($0)",
        category: "json",
    },
    BuiltinFn {
        name: "json_is_null",
        params: "value: Any",
        return_type: "Bool",
        description: "Check if value is null",
        snippet: "json_is_null($0)",
        category: "json",
    },
    BuiltinFn {
        name: "json_is_object",
        params: "value: Any",
        return_type: "Bool",
        description: "Check if value is object",
        snippet: "json_is_object($0)",
        category: "json",
    },
    BuiltinFn {
        name: "json_is_array",
        params: "value: Any",
        return_type: "Bool",
        description: "Check if value is array",
        snippet: "json_is_array($0)",
        category: "json",
    },

    // === std.net - HTTP ===
    BuiltinFn {
        name: "http_get",
        params: "url: String",
        return_type: "Map|Error",
        description: "HTTP GET request, returns {status, body, ok}",
        snippet: "http_get($0)",
        category: "net",
    },
    BuiltinFn {
        name: "http_get_json",
        params: "url: String",
        return_type: "Any|Error",
        description: "HTTP GET and parse JSON response",
        snippet: "http_get_json($0)",
        category: "net",
    },
    BuiltinFn {
        name: "http_post",
        params: "url: String, body: String|Map",
        return_type: "Map|Error",
        description: "HTTP POST request",
        snippet: "http_post($1, $2)",
        category: "net",
    },
    BuiltinFn {
        name: "http_post_json",
        params: "url: String, body: Map",
        return_type: "Any|Error",
        description: "HTTP POST JSON and parse response",
        snippet: "http_post_json($1, $2)",
        category: "net",
    },
    BuiltinFn {
        name: "http_put",
        params: "url: String, body: String|Map",
        return_type: "Map|Error",
        description: "HTTP PUT request",
        snippet: "http_put($1, $2)",
        category: "net",
    },
    BuiltinFn {
        name: "http_delete",
        params: "url: String",
        return_type: "Map|Error",
        description: "HTTP DELETE request",
        snippet: "http_delete($0)",
        category: "net",
    },
    BuiltinFn {
        name: "http_head",
        params: "url: String",
        return_type: "Map|Error",
        description: "HTTP HEAD request",
        snippet: "http_head($0)",
        category: "net",
    },
    BuiltinFn {
        name: "http_request",
        params: "method: String, url: String, headers: Map?, body: Any?",
        return_type: "Map|Error",
        description: "Generic HTTP request with custom options",
        snippet: "http_request(\"$1\", $2, $3, $4)",
        category: "net",
    },
    BuiltinFn {
        name: "url_encode",
        params: "s: String",
        return_type: "String",
        description: "URL-encode string",
        snippet: "url_encode($0)",
        category: "net",
    },
    BuiltinFn {
        name: "url_decode",
        params: "s: String",
        return_type: "String",
        description: "URL-decode string",
        snippet: "url_decode($0)",
        category: "net",
    },
];

/// Keywords with documentation
pub const KEYWORDS: &[(&str, &str, &str)] = &[
    ("let", "Local variable binding", "let $1 = $2 : $0"),
    ("if", "Conditional expression", "if $1 { $2 } else { $0 }"),
    ("true", "Boolean true literal", "true"),
    ("false", "Boolean false literal", "false"),
    ("nil", "Nil/null value", "nil"),
    ("mod", "Module declaration", "mod $0"),
    ("use", "Import from module", "use $1.{$0}"),
    ("type", "Type alias definition", "type $1 = $0"),
    ("pub", "Public visibility modifier", "pub "),
];

/// Collection operators
pub const OPERATORS: &[(&str, &str, &str)] = &[
    (".@", "Map operation - transform each element", ".@($0)"),
    (".?", "Filter operation - keep matching elements", ".?($0)"),
    ("./", "Reduce operation with custom function", "./(0, $0)"),
    ("./+", "Sum reduce - add all elements", "./+"),
    ("./*", "Product reduce - multiply all elements", "./*"),
    ("./min", "Min reduce - find minimum", "./min"),
    ("./max", "Max reduce - find maximum", "./max"),
    ("$", "Self-recursion operator", "$($0)"),
    ("#", "Length operator", "#$0"),
    ("..", "Range operator", "$1..$2"),
    ("?:", "Contains operator", "$1 ?: $2"),
];
